### ISSUE TITLE
Request for Training details and Pre-trained Models

### ISSUE THREAD

**Issue by zhang-lie** [ffhibnese/CGNC_Targeted_Adversarial_Attacks#1]
Thanks for the nice work. I have a few questions/requests:

1 - Can you please release the pre-trained models for reproducibility?
2 - Can you tell how many and what GPUs you used for training and how much time it took?

**Comment by ffhibnese** [comment]
Thanks for your attention to our work!
1. We will prepare a Google Driver link that includes the pre-trained generators soon. Please keep track of recent updates in our Readme.
2. The generator training costs nearly 25h and 47h on a single NVIDIA 3090 when the surrogates are Res152 and Inc-v3 respectively.  The consuming hours will be reduced to 15h and 26h for parallel training on two NVIDIA 3090 GPUS.

**Comment by zhang-lie** [comment]
Thanks for your response. Also we observe that the numbers in Table 1 for Inc-v4 and Inc-Res-v2 for the baseline C-GSP [1] (highlighted in the red box) are not matching with the original C-GSP paper (2nd table below). However, for the other columns (highlighted in green), the values are the same as mentioned in the original paper [1]. Is there any specific reason for this discrepancy?

[1] - Boosting Transferability of Targeted Adversarial Examples via Hierarchical Generative Networks

![issue](https://github.com/user-attachments/assets/9c6740f2-b756-4aca-9d91-f0d4fe315f8e)
![issue_1](https://github.com/user-attachments/assets/e74ed755-8814-461f-8cef-295eef3e9d3a)

**Comment by ffhibnese** [comment]
Good question! C-GSP **does not provide their pre-trained weights** of Incv4 and IR-v2. We also do not know the detailed structure they used or how they initialize and train the model. 
To solve this, we import the pre-trained classifiers (Incv4 and IR-v2) from the pubic package `timm` and faithfully reproduce C-GSP using their released pre-trained generators. The exact results are presented in our tables and the comparison is fair and reliable under the same settings. You can easily reproduce these values based on our code with the released pre-trained generators from C-GSP.
We hope our work can **rectify this performance mismatching** for these two models in former studies and formulate **a uniform and correct comparison**.

**Comment by fengyao12** [comment]
> Thanks for your attention to our work!
> 
> 1. We will prepare a Google Driver link that includes the pre-trained generators soon. Please keep track of recent updates in our Readme.
> 2. The generator training costs nearly 25h and 47h on a single NVIDIA 3090 when the surrogates are Res152 and Inc-v3 respectively.  The consuming hours will be reduced to 15h and 26h for parallel training on two NVIDIA 3090 GPUS.

Why does it take 13 hours to run just one epoch? I’m using four 3090 GPUs.
![WechatIMG670](https://github.com/user-attachments/assets/18a87d0a-2095-42e7-b5e9-1d561daf354f)

**Comment by ffhibnese** [comment]
> > Thanks for your attention to our work!
> > 
> > 1. We will prepare a Google Driver link that includes the pre-trained generators soon. Please keep track of recent updates in our Readme.
> > 2. The generator training costs nearly 25h and 47h on a single NVIDIA 3090 when the surrogates are Res152 and Inc-v3 respectively.  The consuming hours will be reduced to 15h and 26h for parallel training on two NVIDIA 3090 GPUS.
> 
> Why does it take 13 hours to run just one epoch? I’m using four 3090 GPUs. ![WechatIMG670](https://private-user-images.githubusercontent.com/154896904/363460205-18a87d0a-2095-42e7-b5e9-1d561daf354f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjkwMjYsIm5iZiI6MTcyNTE2ODcyNiwicGF0aCI6Ii8xNTQ4OTY5MDQvMzYzNDYwMjA1LTE4YTg3ZDBhLTIwOTUtNDJlNy1iNWU5LTFkNTYxZGFmMzU0Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzViM2Y0NWY0MDZjNTQwYzUwZGMxYjNjYTg0NzBhOTgxYzNmNjE5NTRjM2E0YTliYzNmNjRiZDdhYTYzYmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nojbcuYYjp_EJw_o4J1pdmPjgIE9KGusxbq5uz0vomU)

Normally, the running time does not decrease linearly with the number of GPUs you use due to the communication budget between GPUs. And from our experience, 13 hours per epoch is reasonable.

**Comment by fengyao12** [comment]
> > > Thanks for your attention to our work!
> > > 
> > > 1. We will prepare a Google Driver link that includes the pre-trained generators soon. Please keep track of recent updates in our Readme.
> > > 2. The generator training costs nearly 25h and 47h on a single NVIDIA 3090 when the surrogates are Res152 and Inc-v3 respectively.  The consuming hours will be reduced to 15h and 26h for parallel training on two NVIDIA 3090 GPUS.
> > 
> > 
> > Why does it take 13 hours to run just one epoch? I’m using four 3090 GPUs. ![WechatIMG670](https://private-user-images.githubusercontent.com/154896904/363460205-18a87d0a-2095-42e7-b5e9-1d561daf354f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjkwMjYsIm5iZiI6MTcyNTE2ODcyNiwicGF0aCI6Ii8xNTQ4OTY5MDQvMzYzNDYwMjA1LTE4YTg3ZDBhLTIwOTUtNDJlNy1iNWU5LTFkNTYxZGFmMzU0Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzViM2Y0NWY0MDZjNTQwYzUwZGMxYjNjYTg0NzBhOTgxYzNmNjE5NTRjM2E0YTliYzNmNjRiZDdhYTYzYmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nojbcuYYjp_EJw_o4J1pdmPjgIE9KGusxbq5uz0vomU)
> 
> Normally, the running time does not decrease linearly with the number of GPUs you use due to the communication budget between GPUs. And from our experience, 13 hours per epoch is reasonable.

Thanks for your reply，in other words, The time mentioned in your second response refers to the duration required for a single epoch?

**Comment by ffhibnese** [comment]
> > > > Thanks for your attention to our work!
> > > > 
> > > > 1. We will prepare a Google Driver link that includes the pre-trained generators soon. Please keep track of recent updates in our Readme.
> > > > 2. The generator training costs nearly 25h and 47h on a single NVIDIA 3090 when the surrogates are Res152 and Inc-v3 respectively.  The consuming hours will be reduced to 15h and 26h for parallel training on two NVIDIA 3090 GPUS.
> > > 
> > > 
> > > Why does it take 13 hours to run just one epoch? I’m using four 3090 GPUs. ![WechatIMG670](https://private-user-images.githubusercontent.com/154896904/363460205-18a87d0a-2095-42e7-b5e9-1d561daf354f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjkwMjYsIm5iZiI6MTcyNTE2ODcyNiwicGF0aCI6Ii8xNTQ4OTY5MDQvMzYzNDYwMjA1LTE4YTg3ZDBhLTIwOTUtNDJlNy1iNWU5LTFkNTYxZGFmMzU0Zi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzViM2Y0NWY0MDZjNTQwYzUwZGMxYjNjYTg0NzBhOTgxYzNmNjE5NTRjM2E0YTliYzNmNjRiZDdhYTYzYmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nojbcuYYjp_EJw_o4J1pdmPjgIE9KGusxbq5uz0vomU)
> > 
> > 
> > Normally, the running time does not decrease linearly with the number of GPUs you use due to the communication budget between GPUs. And from our experience, 13 hours per epoch is reasonable.
> 
> Thanks for your reply，in other words, The time mentioned in your second response refers to the duration required for a single epoch?

Yes, it's the duration per epoch.
