### ISSUE TITLE
Clarification about cross-domain scenario

### ISSUE THREAD

**Issue by tgoncalv** [ffhibnese/CGNC_Targeted_Adversarial_Attacks#3]
Thank you for your great work and repository !

I want to ask you a question about the cross-domain experience. If I understand it correctly, you use COCO/Comics dataset during training, and Res152 as a surrogate model right ? More precisely, I want to know if the surrogate model has been pre-trained on ImageNet or not. Otherwise I don't understand how you would be able to set 8 targets during training and the same 8 targets during evaluation (using NeurIPS ImageNet evaluation dataset).

![image](https://github.com/user-attachments/assets/cbe31360-3619-47c0-a7ac-8402fc98dde5)

**Comment by tgoncalv** [comment]
I have another question about "large number of classes"

For example, CGNC(res152) has ~58%/59% accuracy on the figure6 (using 8 targets), which is not consistent with any of the values reported on table1. I would like to know the settings you used to run the evaluation. Thank you so much for your attention !

![image](https://github.com/user-attachments/assets/69cd9c91-0dc5-4d73-8e13-851aec702789)

**Comment by KongJiawei1231** [comment]
> Thank you for your great work and repository !
> 
> I want to ask you a question about the cross-domain experience. If I understand it correctly, you use COCO/Comics dataset during training, and Res152 as a surrogate model right ? More precisely, I want to know if the surrogate model has been pre-trained on ImageNet or not. Otherwise I don't understand how you would be able to set 8 targets during training and the same 8 targets during evaluation (using NeurIPS ImageNet evaluation dataset).
> 
> ![image](https://private-user-images.githubusercontent.com/75808762/371762005-cbe31360-3619-47c0-a7ac-8402fc98dde5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Nzg2OTYsIm5iZiI6MTcyNzU3ODM5NiwicGF0aCI6Ii83NTgwODc2Mi8zNzE3NjIwMDUtY2JlMzEzNjAtMzYxOS00N2MwLWE3YWMtODQwMmZjOThkZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAyNTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMzlmN2RjNzdhZDRlOTZlNzQxOGZkM2I5NGFjOTE0OTYyYzVjMmMxZGRkMzU2ZWVmNmEzNGMzYWVlMTQxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MtVfgU1j_FcRaZlch7OH80n7Xa1rr6jqT91SBnhnzUU)

Thanks for your interest!
As you understand, we use the surrogate model pre-trained on ImageNet. We set 8 targets via specifying the text conditions and the target labels during training. In the evaluation stage, we randomly select 1000 images from the source dataset and specify the text condition of the target class to generate adversarial samples.

**Comment by KongJiawei1231** [comment]
> I have another question about "large number of classes"
> 
> For example, CGNC(res152) has ~58%/59% accuracy on the figure6 (using 8 targets), which is not consistent with any of the values reported on table1. I would like to know the settings you used to run the evaluation. Thank you so much for your attention !
> 
> ![image](https://private-user-images.githubusercontent.com/75808762/371762220-69cd9c91-0dc5-4d73-8e13-851aec702789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1Nzk2MzEsIm5iZiI6MTcyNzU3OTMzMSwicGF0aCI6Ii83NTgwODc2Mi8zNzE3NjIyMjAtNjljZDljOTEtMGRjNS00ZDczLThlMTMtODUxYWVjNzAyNzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAzMDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NGYzMWE5NWNjZDE1NGFiZDkxMjk5ZTAyMTg4ZWY3MGU0ZTE5MjE5NDdlNDRjMDEyMDFiODcxZDkzOWM3MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YVr1uVPLBMaNtjRvAYP8TdBtZ9NhuexQYF7WTu8zhoM)

In Fig.6, the target fooling rate is calculated by the average ASR of black-box models. To be specific, when employing Res-152 as the surrogate model, we use the average ASR of Inc-v3, Inc-v4, Inc-Res-v2, DN-121, GoogleNet and VGG-16, i.e. 58.40%, as the target fooling rate.

**Comment by tgoncalv** [comment]
Thank you very much for your answer !

**Comment by KongJiawei1231** [comment]
> I have another question about "large number of classes"
> 
> For example, CGNC(res152) has ~58%/59% accuracy on the figure6 (using 8 targets), which is not consistent with any of the values reported on table1. I would like to know the settings you used to run the evaluation. Thank you so much for your attention !
> 
> ![image](https://private-user-images.githubusercontent.com/75808762/371762220-69cd9c91-0dc5-4d73-8e13-851aec702789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODA4ODgsIm5iZiI6MTcyNzU4MDU4OCwicGF0aCI6Ii83NTgwODc2Mi8zNzE3NjIyMjAtNjljZDljOTEtMGRjNS00ZDczLThlMTMtODUxYWVjNzAyNzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDAzMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMTI0M2E4MTc0YTg2MzRlOWQwMWRhMjBlMDA3ZGYwYzk3NDAxYmEzZGM5ZTEzZjQwNDk5NmI0NjA4MWZkNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SLUpOVBlzTLE6aUg8aLXK-NFH79NMHqaTsYPswD4eRI)

We apologize for not having clearly explained the experimental setting in our paper. In Fig.6, the target fooling rate is calculated by the average ASR of black-box models. To be specific, when employing Res-152 as the surrogate model, we use the average ASR of Inc-v3, Inc-v4, Inc-Res-v2, DN-121, GoogleNet and VGG-16, i.e. 58.40%, as the target fooling rate.
